name: lint

on: [push]

jobs:
  fawltydeps-api:
    name: FawltyDeps (API)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install FawltyDeps
        run: pip install fawltydeps
      - name: Check API dependencies
        run: fawltydeps --detailed
        working-directory: api
