name: lint

on: [push]

jobs:
  lint:
    name: FawltyDeps
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: FawltyDeps
        uses: tweag/FawltyDeps-action@v0.2.0
