name: lint

on: [push]

jobs:
  fawltydeps-api:
    name: FawltyDeps (API)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check API dependencies
        uses: tweag/FawltyDeps-action@v0.2.0
        with:
          # Run fawltydeps in the api/ directory
          options: --detailed --base-dir=api

  fawltydeps-training:
    name: FawltyDeps (Training)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Training dependencies
        uses: tweag/FawltyDeps-action@v0.2.0
        with:
          # Run fawltydeps in the training/ directory
          options: --detailed --base-dir=training
